#
# Makefile for building and checking a static library
#

BUILD = ../../../build

DIRS=buildlib checklib

all:
		for i in $(DIRS) ; do \
		  $(MAKE) -C $$i all ; \
		done

clean:
		for i in $(DIRS) ; do \
		  $(MAKE) -C $$i clean ; \
		done
		rm -f *~
