#
# Makefile
#

all:
		gcc -g -Wall -o fabs-gnu -I../../../lib/include fabs.c
		#gcc -g -Wall -o fabs-gnu fabs.c -lm
		#gcc -g -Wall -o fabs-eco fabs.c ../../../lib/libm/fabs.c

install:

clean:
		rm -f *~ fabs-gnu fabs-eco
