#
# Makefile for standalone library
#

BUILD = ../build

all:

install:
		mkdir -p $(BUILD)/include
		cp ./include/* $(BUILD)/include
		mkdir -p $(BUILD)/lib
		cp ./scripts/* $(BUILD)/lib

clean:
		rm -f *~
