#
# Makefile for FPGA implementations of ECO32
#

BUILD = ../build

DIRS = tests mc mc-sim mc-vl pl pl-sim pl-vl

.PHONY:		all install clean

all:
		for i in $(DIRS) ; do \
		  $(MAKE) -C $$i all ; \
		done

install:
		for i in $(DIRS) ; do \
		  $(MAKE) -C $$i install ; \
		done

clean:
		for i in $(DIRS) ; do \
		  $(MAKE) -C $$i clean ; \
		done
		rm -f *~
