#
# Makefile for FPGA implementations of ECO32
#

.PHONY:		all install clean

all:

install:

clean:
		mv xsa-xst-3/eco32.ucf .
		mv xsa-xst-3/eco32.xise .
		rm -rf xsa-xst-3/*
		mv eco32.ucf xsa-xst-3
		mv eco32.xise xsa-xst-3
		rm -f *~
