#
# Makefile for FPGA implementations of ECO32
#

BUILD = ../../../build

.PHONY:		all install clean

all:
#all:		xsa-xst-3/eco32.bit

install:
#install:	xsa-xst-3/eco32.bit
#		$(BUILD)/bin/bit2exo 0x180000 \
#		  xsa-xst-3/eco32.bit xsa-xst-3/eco32.exo
#		mkdir -p $(BUILD)/eco32/xsa-xst-3
#		cp xsa-xst-3/eco32.bit $(BUILD)/eco32/xsa-xst-3
#		cp xsa-xst-3/eco32.exo $(BUILD)/eco32/xsa-xst-3

clean:
#		mv xsa-xst-3/eco32.ucf .
#		mv xsa-xst-3/eco32.xise .
#		mv xsa-xst-3/eco32.bit .
#		rm -rf xsa-xst-3/*
#		mv eco32.ucf xsa-xst-3
#		mv eco32.xise xsa-xst-3
#		mv eco32.bit xsa-xst-3
		rm -f *~
